project:
  type: website

website:
  title: "National Park Climate Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/lindsaystrong7/dsan-scholarship-project
        text: Code
        icon: github
      - href: about.qmd
        text: Citations


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



