project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://github.com/lindsaystrong7/dsan-scholarship-project
        text: Code
        icon: github


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



